name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone Rapid Theme
        uses: actions/checkout@v2
        with:
          repository: acdzh/gatsby-theme-rapid
          path: .
      - name: ls
        run: tree
      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          repository: acdzh/gatsby-blog-src
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./content
      - name: ls
        run: tree
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages